import warnings
from pathlib import Path

import numpy as np

warnings.filterwarnings("ignore")
np.random.seed(42)

IN_SAMPLE_START = "2015"
IN_SAMPLE_END = "2017"
OUT_SAMPLE_START = "2018"
OUT_SAMPLE_END = "2025"

MIN_DATA_AVAILABILITY = 0.90
NETWORK_THRESHOLD_QUANTILE = 0.80
HIER_MAX_CLUSTERS = 10
HERC_MAX_DEPTH = 10
PERIODS_PER_YEAR = 252

KMEANS_K = 4
# KMEANS_ELBOW_MIN_K = 2
# KMEANS_ELBOW_MAX_K = 12
KMEANS_SCALE_FEATURES = True
KMEANS_REMOVE_OUTLIERS = True
KMEANS_OUTLIER_Z = 3.5
KMEANS_RANDOM_STATE = 42

OUTPUT_DIR = Path("outputs")
