import warnings
from pathlib import Path

import numpy as np

warnings.filterwarnings("ignore")
np.random.seed(42)

IN_SAMPLE_START = "2020-01-01"
IN_SAMPLE_END = "2022-12-31"
OUT_SAMPLE_START = "2023-01-01"
OUT_SAMPLE_END = "2025-12-31"

MIN_DATA_AVAILABILITY = 0.90
MIN_PRICE_THRESHOLD = 0.01

NETWORK_THRESHOLD_QUANTILE = 0.75

HIER_MAX_CLUSTERS = 15
HIER_MIN_CLUSTER_SIZE = None
HERC_MAX_DEPTH = 10
HERC_LINKAGE_METHOD = "ward"
HERC_USE_DISTANCE_OF_DISTANCE = True

KMEANS_K = 4
KMEANS_SCALE_FEATURES = True
KMEANS_REMOVE_OUTLIERS = True
KMEANS_OUTLIER_Z = 3.5
KMEANS_RANDOM_STATE = 42
KMEANS_TOP_CLUSTERS = 2
KMEANS_MIN_CLUSTER_SIZE = 4

PERIODS_PER_YEAR = 252

OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)
